version: '3.9'

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-fpm-bookworm:latest
    container_name: php_fpm_bench
    hostname: php-fpm
    environment:
      - CI_ENV=production
    volumes:
      - ./www/html:/var/www/html:cached
      - ./conf:/usr/local/etc:cached
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: clearlinux/redis
    container_name: redis_bench
    hostname: redis

  nginx:
    image: clearlinux/nginx
    container_name: nginx_bench
    hostname: nginx
    volumes:
      - ./www/html:/var/www/html:cached
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80

  python:
    image: bench/python3
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: python3_bench
    hostname: python3

  database:
    image: mariadb:10.2
    container_name: mariadb_bench
    hostname: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --disable-log-bin
    volumes:
      - ./src/db/films.sql:/tmp/films.sql
      - ./conf/mariadb/data:/var/lib/mysql:delegated
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=your-very-long-passwd
      - MYSQL_DATABASE=bench
      - MYSQL_USER=bench
      - MYSQL_PASSWORD=bench

