version: '3.9'

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-fpm-bookworm:latest
    container_name: php-fpm
    volumes:
      - ./www/html:/var/www/html:cached
      - ./conf:/usr/local/etc:cached
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: clearlinux/redis
    container_name: redis

  nginx:
    image: clearlinux/nginx
    container_name: nginx
    hostname: nginx
    volumes:
      - ./www/html:/var/www/html:cached
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
