version: '3.9'

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-fpm-bookworm:latest
    container_name: php_fpm_bench
    hostname: php-fpm
    environment:
      - CI_ENV=production
    volumes:
      - ./www/html:/var/www/html:cached
      - ./conf:/usr/local/etc:cached
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: clearlinux/redis
    container_name: redis_bench
    hostname: redis

  nginx:
    image: clearlinux/nginx
    container_name: nginx_bench
    hostname: nginx
    depends_on:
      - php-fpm
    volumes:
      - ./www/html:/var/www/html:cached
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80

  python:
    image: bench/python3
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: python3_bench
    hostname: python3

  database:
    image: clearlinux/mariadb:latest
    container_name: mariadb_bench
    hostname: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed --disable-log-bin
    volumes:
      - ./conf/mariadb:/usr/share/defaults/mariadb/my.cnf.d
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=verydifficultpasswd
      - MYSQL_DATABASE=bench
      - MYSQL_USER=bench
      - MYSQL_PASSWORD=bench

